// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using neck.Models;
using System;

namespace neck.Migrations
{
	[DbContext(typeof(NeckContext))]
    partial class NeckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("neck.Models.Db.ChordVariation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Barre")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Label")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Positions")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Updated")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("ChordVariations");
            });

            modelBuilder.Entity("neck.Models.Db.Tuning", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("Created")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Offsets")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("Updated")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("Tuning");
            });
#pragma warning restore 612, 618
        }
    }
}
